package codegen

import (
	"fmt"
	"karkain/pkg/parser"
	"math"
	"strings"
)

// ============================================================
// Phase 32: OpenQASM 3.0 Pulse Control Generator (OpenPulse)
// Generates defcal blocks, frame definitions, and pulse envelopes
// for low-level QPU control.
// ============================================================

// PulseBackend configures the pulse-level code generation
type PulseBackend struct {
	GateTime       int    // gate duration in dt (discrete time units)
	SampleRate     int    // DAC sample rate
	FramePrefix    string // prefix for frame names
	CalibrationSet string // name of the calibration set
}

// DefaultPulseBackend returns a sensible default configuration
func DefaultPulseBackend() PulseBackend {
	return PulseBackend{
		GateTime:       160,
		SampleRate:     1e9, // 1 GHz
		FramePrefix:    "q",
		CalibrationSet: "default",
	}
}

// PulseEnvelopeType defines the type of pulse envelope
type PulseEnvelopeType int

const (
	EnvelopeGaussian PulseEnvelopeType = iota
	EnvelopeGaussianDerivative
	EnvelopeDrag
	EnvelopeSquare
	EnvelopeConstant
	EnvelopeRiseFall
)

// PulseFrame represents a hardware control frame
type PulseFrame struct {
	Name     string
	Qubit    int
	Type     string // "drive", "measure", "control", "capture"
	Frequency float64
}

// PulseGateCalibration defines the pulse-level calibration for a gate
type PulseGateCalibration struct {
	GateName   string
	Qubit      int
	Angle      float64
	Frame      PulseFrame
	Envelope   PulseEnvelopeType
	Amplitude  float64
	Duration   int  // in dt
	Sigma      float64 // Gaussian sigma
	DragCoeff  float64 // DRAG coefficient
}

// ============================================================
// OpenPulse Generator
// ============================================================

// OpenPulseGenerator generates OpenQASM 3.0 pulse control code
type OpenPulseGenerator struct {
	buf     strings.Builder
	errors  []string
	backend PulseBackend
	frames  []PulseFrame
}

// NewOpenPulseGenerator creates a new pulse control generator
func NewOpenPulseGenerator(backend PulseBackend) *OpenPulseGenerator {
	return &OpenPulseGenerator{
		backend: backend,
	}
}

// GeneratePulseProgram produces a complete OpenQASM 3.0 program with pulse calibration
func (g *OpenPulseGenerator) GeneratePulseProgram(circuit *parser.CircuitDecl, calibrations []PulseGateCalibration) (string, error) {
	g.buf.Reset()
	g.errors = nil
	g.frames = nil

	g.emitHeader()
	g.emitFrameDefinitions(circuit)
	g.emitDefcalBlocks(calibrations)
	g.emitCircuitBody(circuit, calibrations)

	if len(g.errors) > 0 {
		return "", fmt.Errorf("openpulse errors: %s", strings.Join(g.errors, "\n"))
	}
	return g.buf.String(), nil
}

func (g *OpenPulseGenerator) emitHeader() {
	g.buf.WriteString("// Generated by Karkain Compiler v1.1.0 — OpenPulse Extension\n")
	g.buf.WriteString("// Pulse-level control for quantum hardware calibration\n")
	g.buf.WriteString("OPENQASM 3.0;\n")
	g.buf.WriteString("include \"stdgates.inc\";\n")
	g.buf.WriteString("include \"stdpulse.inc\";\n")
	g.buf.WriteString("\n")
}

func (g *OpenPulseGenerator) emitFrameDefinitions(circuit *parser.CircuitDecl) {
	g.buf.WriteString("// ---- Frame Definitions ----\n")

	qubitCount := 0
	for _, p := range circuit.Params {
		if p.Type != nil && p.Type.Size > 0 {
			qubitCount += p.Type.Size
		} else {
			qubitCount++
		}
	}

	for i := 0; i < qubitCount; i++ {
		frameName := fmt.Sprintf("%s%d_drive", g.backend.FramePrefix, i)
		g.frames = append(g.frames, PulseFrame{
			Name:  frameName,
			Qubit: i,
			Type:  "drive",
		})
		g.buf.WriteString(fmt.Sprintf("frame %s = newframe(hardware通道, %d, 0.0);\n", frameName, i))

		// Measure frame
	 measFrameName := fmt.Sprintf("%s%d_measure", g.backend.FramePrefix, i)
		g.frames = append(g.frames, PulseFrame{
			Name:  measFrameName,
			Qubit: i,
			Type:  "measure",
		})
		g.buf.WriteString(fmt.Sprintf("frame %s = newframe(hardware通道, %d, 0.0);\n", measFrameName, i))
	}

	g.buf.WriteString("\n")
}

func (g *OpenPulseGenerator) emitDefcalBlocks(calibrations []PulseGateCalibration) {
	g.buf.WriteString("// ---- Defcal Blocks (Pulse Calibration) ----\n\n")

	for _, cal := range calibrations {
		g.emitSingleDefcal(cal)
	}
}

func (g *OpenPulseGenerator) emitSingleDefcal(cal PulseGateCalibration) {
	frameName := fmt.Sprintf("%s%d_drive", g.backend.FramePrefix, cal.Qubit)

	// Gate signature
	if cal.GateName == "rx" || cal.GateName == "ry" || cal.GateName == "rz" {
		g.buf.WriteString(fmt.Sprintf("defcal %s(angle[angle]) $%d {{\n", cal.GateName, cal.Qubit))
	} else {
		g.buf.WriteString(fmt.Sprintf("defcal %s $%d {{\n", cal.GateName, cal.Qubit))
	}

	// Pulse envelope
	g.buf.WriteString(fmt.Sprintf("    play(%s, %s(", frameName, envelopeFuncName(cal.Envelope)))
	g.buf.WriteString(fmt.Sprintf("amp=%s", g.formatAmplitude(cal.Amplitude)))
	g.buf.WriteString(fmt.Sprintf(", duration=%d dt", cal.Duration))
	if cal.Envelope == EnvelopeGaussian || cal.Envelope == EnvelopeDrag {
		g.buf.WriteString(fmt.Sprintf(", sigma=%d dt", int(cal.Sigma)))
	}
	if cal.Envelope == EnvelopeDrag && cal.DragCoeff != 0 {
		g.buf.WriteString(fmt.Sprintf(", beta=%.4f", cal.DragCoeff))
	}
	g.buf.WriteString("));\n")

	g.buf.WriteString("}\n\n")
}

func (g *OpenPulseGenerator) emitCircuitBody(circuit *parser.CircuitDecl, calibrations []PulseGateCalibration) {
	g.buf.WriteString("// ---- Circuit Body (uses calibrated pulses) ----\n")

	calMap := make(map[string]PulseGateCalibration)
	for _, cal := range calibrations {
		key := fmt.Sprintf("%s_%d_%.4f", cal.GateName, cal.Qubit, cal.Angle)
		calMap[key] = cal
	}

	for _, stmt := range circuit.Body {
		switch n := stmt.(type) {
		case *parser.QPUOpExpr:
			g.emitPulseGateOp(n, calMap)
		case *parser.ExprStmt:
			if qpu, ok := n.Expression.(*parser.QPUOpExpr); ok {
				g.emitPulseGateOp(qpu, calMap)
			}
		}
	}
}

func (g *OpenPulseGenerator) emitPulseGateOp(op *parser.QPUOpExpr, calMap map[string]PulseGateCalibration) {
	qubitIdx := 0
	if len(op.Args) > 0 {
		qubitIdx = resolveQubitIdxPulse(op.Args[0])
	}

	switch op.Op {
	case "rx", "ry", "rz":
		g.buf.WriteString(fmt.Sprintf("%s(%.4f) $%d;\n", op.Op, g.resolveAngle(op.Angle), qubitIdx))
	case "h", "x", "y", "z":
		g.buf.WriteString(fmt.Sprintf("%s $%d;\n", op.Op, qubitIdx))
	case "cx":
		ctrl := 0
		tgt := 0
		if len(op.Args) > 1 {
			ctrl = resolveQubitIdxPulse(op.Args[0])
			tgt = resolveQubitIdxPulse(op.Args[1])
		}
		g.buf.WriteString(fmt.Sprintf("cx $%d, $%d;\n", ctrl, tgt))
	case "measure":
		for _, arg := range op.Args {
			idx := resolveQubitIdxPulse(arg)
			g.buf.WriteString(fmt.Sprintf("measure $%d -> c[%d];\n", idx, idx))
		}
	default:
		g.buf.WriteString(fmt.Sprintf("// %s gate\n", op.Op))
	}
}

// ============================================================
// Pulse Envelope Generators
// ============================================================

// GaussianPulse generates a Gaussian pulse envelope specification
func GaussianPulse(amplitude, sigma float64, duration int) string {
	return fmt.Sprintf("gaussian(amp=%.6f, duration=%d dt, sigma=%d dt)", amplitude, duration, int(sigma))
}

// DragPulse generates a DRAG (Derivative Removal by Adiabatic Gate) pulse
func DragPulse(amplitude, sigma, beta float64, duration int) string {
	return fmt.Sprintf("drag(amp=%.6f, duration=%d dt, sigma=%d dt, beta=%.4f)", amplitude, duration, int(sigma), beta)
}

// SquarePulse generates a square/constant pulse
func SquarePulse(amplitude float64, duration int) string {
	return fmt.Sprintf("square(amp=%.6f, duration=%d dt)", amplitude, duration)
}

// RiseFallPulse generates a rise-fall (cosine) pulse
func RiseFallPulse(amplitude float64, duration int) string {
	return fmt.Sprintf("risefall(amp=%.6f, duration=%d dt)", amplitude, duration)
}

// ============================================================
// Pulse Sequence Generator
// ============================================================

// PulseSequence represents a sequence of pulse operations
type PulseSequence struct {
	Operations []PulseOp
}

// PulseOp represents a single pulse operation
type PulseOp struct {
	Type     string  // "play", "setfrequency", "shiftphase", "capture"
	Frame    string
	Waveform string
	Duration int
}

// GeneratePulseSequence converts a list of gate calibrations to a pulse sequence
func GeneratePulseSequence(circuit *parser.CircuitDecl, calibrations []PulseGateCalibration) *PulseSequence {
	seq := &PulseSequence{}
	calMap := make(map[string]PulseGateCalibration)
	for _, cal := range calibrations {
		key := fmt.Sprintf("%s_%d", cal.GateName, cal.Qubit)
		calMap[key] = cal
	}

	for _, stmt := range circuit.Body {
		switch n := stmt.(type) {
		case *parser.QPUOpExpr:
			seq.addGatePulses(n, calMap)
		case *parser.ExprStmt:
			if qpu, ok := n.Expression.(*parser.QPUOpExpr); ok {
				seq.addGatePulses(qpu, calMap)
			}
		}
	}
	return seq
}

func (seq *PulseSequence) addGatePulses(op *parser.QPUOpExpr, calMap map[string]PulseGateCalibration) {
	qubitIdx := 0
	if len(op.Args) > 0 {
		qubitIdx = resolveQubitIdxPulse(op.Args[0])
	}

	key := fmt.Sprintf("%s_%d", op.Op, qubitIdx)
	if cal, ok := calMap[key]; ok {
		frameName := fmt.Sprintf("q%d_drive", qubitIdx)
		waveform := calWaveform(cal)
		seq.Operations = append(seq.Operations, PulseOp{
			Type:     "play",
			Frame:    frameName,
			Waveform: waveform,
			Duration: cal.Duration,
		})
	}
}

func calWaveform(cal PulseGateCalibration) string {
	switch cal.Envelope {
	case EnvelopeDrag:
		return DragPulse(cal.Amplitude, cal.Sigma, cal.DragCoeff, cal.Duration)
	case EnvelopeSquare:
		return SquarePulse(cal.Amplitude, cal.Duration)
	case EnvelopeRiseFall:
		return RiseFallPulse(cal.Amplitude, cal.Duration)
	default:
		return GaussianPulse(cal.Amplitude, cal.Sigma, cal.Duration)
	}
}

// ============================================================
// Amplitude & Calibration Table Generator
// ============================================================

// CalibrationTableGenerator generates hardware-specific calibration data
type CalibrationTableGenerator struct {
	buf strings.Builder
}

func NewCalibrationTableGenerator() *CalibrationTableGenerator {
	return &CalibrationTableGenerator{}
}

// GenerateCalibrationTable produces a calibration table in JSON-like format
func (ct *CalibrationTableGenerator) GenerateCalibrationTable(calibrations []PulseGateCalibration) string {
	ct.buf.Reset()
	ct.buf.WriteString("// Karkain Calibration Table — Hardware-Specific Pulse Parameters\n")
	ct.buf.WriteString("calibration_table {\n")

	for _, cal := range calibrations {
		ct.buf.WriteString(fmt.Sprintf("  gate: %s, qubit: %d,\n", cal.GateName, cal.Qubit))
		ct.buf.WriteString(fmt.Sprintf("    amplitude: %.6f, duration: %d dt,\n", cal.Amplitude, cal.Duration))
		ct.buf.WriteString(fmt.Sprintf("    sigma: %.2f dt, envelope: %s,\n", cal.Sigma, envelopeName(cal.Envelope)))
		if cal.DragCoeff != 0 {
			ct.buf.WriteString(fmt.Sprintf("    drag_beta: %.4f,\n", cal.DragCoeff))
		}
	}

	ct.buf.WriteString("}\n")
	return ct.buf.String()
}

// ============================================================
// Helper functions
// ============================================================

func envelopeFuncName(env PulseEnvelopeType) string {
	switch env {
	case EnvelopeGaussian:
		return "gaussian"
	case EnvelopeGaussianDerivative:
		return "gaussian_deriv"
	case EnvelopeDrag:
		return "drag"
	case EnvelopeSquare:
		return "square"
	case EnvelopeConstant:
		return "constant"
	case EnvelopeRiseFall:
		return "risefall"
	default:
		return "gaussian"
	}
}

func envelopeName(env PulseEnvelopeType) string {
	switch env {
	case EnvelopeGaussian:
		return "gaussian"
	case EnvelopeGaussianDerivative:
		return "gaussian_derivative"
	case EnvelopeDrag:
		return "drag"
	case EnvelopeSquare:
		return "square"
	case EnvelopeConstant:
		return "constant"
	case EnvelopeRiseFall:
		return "risefall"
	default:
		return "unknown"
	}
}

func (g *OpenPulseGenerator) formatAmplitude(amp float64) string {
	return fmt.Sprintf("%.6f", amp)
}

func (g *OpenPulseGenerator) resolveAngle(node parser.Node) float64 {
	if node == nil {
		return 0.0
	}
	switch n := node.(type) {
	case *parser.Float64Literal:
		val := 0.0
		fmt.Sscanf(n.Value, "%f", &val)
		return val
	case *parser.IntLiteral:
		val := 0
		fmt.Sscanf(n.Value, "%d", &val)
		return float64(val)
	default:
		return 0.0
	}
}

func resolveQubitIdxPulse(node parser.Node) int {
	switch n := node.(type) {
	case *parser.QubitIndexExpr:
		if lit, ok := n.Index.(*parser.IntLiteral); ok {
			val := 0
			fmt.Sscanf(lit.Value, "%d", &val)
			return val
		}
		return 0
	case *parser.Identifier:
		return 0
	default:
		return 0
	}
}

// StandardCalibrationSet returns a typical set of pulse calibrations
func StandardCalibrationSet() []PulseGateCalibration {
	return []PulseGateCalibration{
		{GateName: "x", Qubit: 0, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "y", Qubit: 0, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "rx", Qubit: 0, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "ry", Qubit: 0, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "rz", Qubit: 0, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeGaussian},
		{GateName: "h", Qubit: 0, Amplitude: 0.15, Duration: 320, Sigma: 80, Envelope: EnvelopeGaussian},
		{GateName: "cx", Qubit: 0, Amplitude: 0.4, Duration: 300, Sigma: 60, Envelope: EnvelopeGaussian},
		{GateName: "x", Qubit: 1, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "y", Qubit: 1, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "rx", Qubit: 1, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "ry", Qubit: 1, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeDrag, DragCoeff: 0.2},
		{GateName: "rz", Qubit: 1, Amplitude: 0.3, Duration: 160, Sigma: 40, Envelope: EnvelopeGaussian},
		{GateName: "cx", Qubit: 1, Amplitude: 0.4, Duration: 300, Sigma: 60, Envelope: EnvelopeGaussian},
	}
}

// Suppress unused import warnings
var _ = math.Sqrt
