package codegen

import (
	"fmt"
	"karkain/pkg/parser"
	"strings"
)

// OpenQASMGenerator generates OpenQASM 3.0 code from circuit declarations
type OpenQASMGenerator struct {
	buf       strings.Builder
	errors    []string
	qubitMap  map[string]int // qubit name -> register index
	nextReg   int
}

// NewOpenQASMGenerator creates a new OpenQASM 3.0 generator
func NewOpenQASMGenerator() *OpenQASMGenerator {
	return &OpenQASMGenerator{
		qubitMap: make(map[string]int),
	}
}

// GenerateCircuit produces OpenQASM 3.0 code from a CircuitDecl AST node
func (g *OpenQASMGenerator) GenerateCircuit(circuit *parser.CircuitDecl) (string, error) {
	g.buf.Reset()
	g.errors = nil
	g.qubitMap = make(map[string]int)
	g.nextReg = 0

	// Header
	g.buf.WriteString("// Generated by Karkain Compiler v0.14.0\n")
	g.buf.WriteString("OPENQASM 3.0;\n")
	g.buf.WriteString("include \"stdgates.inc\";\n")
	g.buf.WriteString("\n")

	// Declare qubit and classical bit registers
	for _, param := range circuit.Params {
		size := 1
		if param.Type != nil && param.Type.Size > 0 {
			size = param.Type.Size
		}
		g.buf.WriteString(fmt.Sprintf("qubit[%d] %s;\n", size, param.Name))
		g.qubitMap[param.Name] = g.nextReg
		g.nextReg++
	}

	// Declare classical register for return
	if circuit.ReturnType != nil && circuit.ReturnType.Size > 0 {
		g.buf.WriteString(fmt.Sprintf("bit[%d] c;\n", circuit.ReturnType.Size))
	}

	g.buf.WriteString("\n")

	// Generate gate operations
	g.generateBody(circuit.Body)

	return g.buf.String(), nil
}

// generateBody processes circuit body statements
func (g *OpenQASMGenerator) generateBody(stmts []parser.Node) {
	for _, stmt := range stmts {
		g.generateStatement(stmt)
	}
}

// generateStatement emits OpenQASM for a single statement
func (g *OpenQASMGenerator) generateStatement(stmt parser.Node) {
	switch n := stmt.(type) {
	case *parser.ExprStmt:
		g.generateExpr(n.Expression)
	case *parser.QPUOpExpr:
		g.generateQPUOp(n)
	case *parser.CircuitReturnStmt:
		g.generateReturn(n)
	}
}

// generateExpr emits OpenQASM for an expression
func (g *OpenQASMGenerator) generateExpr(expr parser.Node) {
	switch n := expr.(type) {
	case *parser.QPUOpExpr:
		g.generateQPUOp(n)
	case *parser.MeasureExpr:
		g.generateLegacyMeasure(n)
	}
}

// generateQPUOp emits OpenQASM for a quantum gate operation
func (g *OpenQASMGenerator) generateQPUOp(op *parser.QPUOpExpr) {
	switch op.Op {
	case "h":
		g.buf.WriteString(fmt.Sprintf("h %s;\n", g.formatQubitArg(op.Args[0])))
	case "x":
		g.buf.WriteString(fmt.Sprintf("x %s;\n", g.formatQubitArg(op.Args[0])))
	case "y":
		g.buf.WriteString(fmt.Sprintf("y %s;\n", g.formatQubitArg(op.Args[0])))
	case "z":
		g.buf.WriteString(fmt.Sprintf("z %s;\n", g.formatQubitArg(op.Args[0])))
	case "rx":
		angle := g.formatExpr(op.Angle)
		g.buf.WriteString(fmt.Sprintf("rx(%s) %s;\n", angle, g.formatQubitArg(op.Args[0])))
	case "ry":
		angle := g.formatExpr(op.Angle)
		g.buf.WriteString(fmt.Sprintf("ry(%s) %s;\n", angle, g.formatQubitArg(op.Args[0])))
	case "rz":
		angle := g.formatExpr(op.Angle)
		g.buf.WriteString(fmt.Sprintf("rz(%s) %s;\n", angle, g.formatQubitArg(op.Args[0])))
	case "cx":
		g.buf.WriteString(fmt.Sprintf("cx %s, %s;\n",
			g.formatQubitArg(op.Args[0]), g.formatQubitArg(op.Args[1])))
	case "cz":
		g.buf.WriteString(fmt.Sprintf("cz %s, %s;\n",
			g.formatQubitArg(op.Args[0]), g.formatQubitArg(op.Args[1])))
	case "swap":
		g.buf.WriteString(fmt.Sprintf("swap %s, %s;\n",
			g.formatQubitArg(op.Args[0]), g.formatQubitArg(op.Args[1])))
	case "measure":
		for i, arg := range op.Args {
			g.buf.WriteString(fmt.Sprintf("c[%d] = measure %s;\n", i, g.formatQubitArg(arg)))
		}
	case "reset":
		for _, arg := range op.Args {
			g.buf.WriteString(fmt.Sprintf("reset %s;\n", g.formatQubitArg(arg)))
		}
	default:
		g.errors = append(g.errors, fmt.Sprintf("unknown QPU operation: %s", op.Op))
	}
}

// generateReturn emits classical bit assignments for circuit return
func (g *OpenQASMGenerator) generateReturn(ret *parser.CircuitReturnStmt) {
	switch n := ret.Value.(type) {
	case *parser.Identifier:
		// If returning measured bits, they're already in c[]
		g.buf.WriteString(fmt.Sprintf("// return %s\n", n.Name))
	case *parser.QubitIndexExpr:
		g.buf.WriteString(fmt.Sprintf("// return qubit index\n"))
	default:
		g.buf.WriteString("// return\n")
	}
}

// generateLegacyMeasure handles the legacy MeasureExpr
func (g *OpenQASMGenerator) generateLegacyMeasure(expr *parser.MeasureExpr) {
	qubitStr := g.formatQubitArg(expr.Qubit)
	g.buf.WriteString(fmt.Sprintf("measure %s -> c[%d];\n", qubitStr, g.nextReg))
	g.nextReg++
}

// formatQubitArg formats a qubit argument for OpenQASM output
func (g *OpenQASMGenerator) formatQubitArg(node parser.Node) string {
	switch n := node.(type) {
	case *parser.Identifier:
		return n.Name
	case *parser.QubitIndexExpr:
		qubitName := g.formatQubitArg(n.Qubit)
		index := g.formatExpr(n.Index)
		return fmt.Sprintf("%s[%s]", qubitName, index)
	default:
		return "/* unknown */"
	}
}

// formatExpr formats an expression to a string value
func (g *OpenQASMGenerator) formatExpr(node parser.Node) string {
	if node == nil {
		return ""
	}
	switch n := node.(type) {
	case *parser.Identifier:
		return n.Name
	case *parser.IntLiteral:
		return n.Value
	case *parser.Float64Literal:
		return n.Value
	case *parser.BinaryExpr:
		left := g.formatExpr(n.Left)
		right := g.formatExpr(n.Right)
		return fmt.Sprintf("%s %s %s", left, n.Operator, right)
	default:
		return "/* expr */"
	}
}

// GetErrors returns accumulated errors
func (g *OpenQASMGenerator) GetErrors() []string {
	return g.errors
}
