package codegen

import (
	"fmt"
	"karkain/pkg/sema"
	"strings"
)

// ============================================================
// Phase 33: QEC Syndrome Extraction Circuit Generator
// ============================================================

// QECGenerator produces OpenQASM 3.0 syndrome extraction circuits
// for stabilizer error-correcting codes.
type QECGenerator struct {
	buf    strings.Builder
	errors []string
}

// NewQECGenerator creates a new QEC code generator
func NewQECGenerator() *QECGenerator {
	return &QECGenerator{}
}

// GenerateSyndromeCircuit produces a full syndrome extraction circuit
func (g *QECGenerator) GenerateSyndromeCircuit(code *sema.StabilizerCode, rounds int) (string, error) {
	g.buf.Reset()
	g.errors = nil

	g.emitHeader(code)
	g.emitQubitAllocations(code)
	g.emitSyndromeExtraction(code, rounds)
	g.emitErrorCorrection(code)

	if len(g.errors) > 0 {
		return "", fmt.Errorf("qec errors: %s", strings.Join(g.errors, "\n"))
	}
	return g.buf.String(), nil
}

func (g *QECGenerator) emitHeader(code *sema.StabilizerCode) {
	g.buf.WriteString("// Generated by Karkain Compiler v1.1.0 — QEC Module\n")
	g.buf.WriteString(fmt.Sprintf("// Syndrome extraction for: %s\n", code.Name))
	g.buf.WriteString(fmt.Sprintf("// %d physical qubits, %d logical qubits, distance %d\n",
		code.N, code.K, code.Distance))
	g.buf.WriteString("OPENQASM 3.0;\n")
	g.buf.WriteString("include \"stdgates.inc\";\n")
	g.buf.WriteString("\n")
}

func (g *QECGenerator) emitQubitAllocations(code *sema.StabilizerCode) {
	g.buf.WriteString(fmt.Sprintf("qubit[%d] data;\n", code.N))
	g.buf.WriteString(fmt.Sprintf("qubit[%d] syndrome;\n", code.NumChecks()))
	g.buf.WriteString(fmt.Sprintf("bit[%d] syn_out;\n", code.NumChecks()))
	g.buf.WriteString(fmt.Sprintf("bit[%d] logical_out;\n", code.K))
	g.buf.WriteString("\n")
}

func (g *QECGenerator) emitSyndromeExtraction(code *sema.StabilizerCode, rounds int) {
	for round := 0; round < rounds; round++ {
		g.buf.WriteString(fmt.Sprintf("// ---- Syndrome Round %d ----\n", round+1))

		for i, gen := range code.Generators {
			support := gen.NonIdentityIndices()
			ancIdx := i

			g.buf.WriteString(fmt.Sprintf("// Stabilizer %d: %s\n", i, gen.String()))

			if isXType(gen) {
				g.buf.WriteString(fmt.Sprintf("h syndrome[%d];\n", ancIdx))
			}

			for _, dq := range support {
				if isXType(gen) {
					g.buf.WriteString(fmt.Sprintf("cx data[%d], syndrome[%d];\n", dq, ancIdx))
				} else {
					g.buf.WriteString(fmt.Sprintf("cx syndrome[%d], data[%d];\n", ancIdx, dq))
				}
			}

			if isXType(gen) {
				g.buf.WriteString(fmt.Sprintf("h syndrome[%d];\n", ancIdx))
			}
			g.buf.WriteString(fmt.Sprintf("syn_out[%d] = measure syndrome[%d];\n", ancIdx, ancIdx))
			g.buf.WriteString("\n")
		}
	}
}

func (g *QECGenerator) emitErrorCorrection(code *sema.StabilizerCode) {
	g.buf.WriteString("// ---- Decode and Correct ----\n")
	g.buf.WriteString("// Syndrome lookup and correction (hardware-specific decoder)\n")

	if code.K == 1 && code.Distance == 3 {
		g.buf.WriteString("// Single-error correction:\n")
		g.buf.WriteString("// For each single-qubit X error, the syndrome identifies the qubit.\n")
		g.buf.WriteString("// Apply recovery: flip identified qubit.\n")
		g.buf.WriteString("if (syn_out != 0) {\n")
		g.buf.WriteString("    // Syndrome → correction lookup (example for weight-1 errors)\n")
		for i := 0; i < code.N; i++ {
			g.buf.WriteString(fmt.Sprintf("    // Syndrome for X error on qubit %d\n", i))
		}
		g.buf.WriteString("}\n")
	} else {
		g.buf.WriteString("// Decoder: use minimum-weight perfect matching or lookup table\n")
		g.buf.WriteString("// Recovery operator applied based on syndrome\n")
	}

	g.buf.WriteString("\n// Logical output\n")
	for lq := 0; lq < code.K; lq++ {
		g.buf.WriteString(fmt.Sprintf("logical_out[%d] = measure data[0]; // placeholder\n", lq))
	}
}

func isXType(gen sema.PauliString) bool {
	for _, op := range gen.Ops {
		if op == sema.ECOpX || op == sema.ECOpY {
			return true
		}
	}
	return false
}

// ============================================================
// Surface Code Syndrome Circuit Generator
// ============================================================

// SurfaceCodeGenerator generates syndrome circuits for surface codes
type SurfaceCodeGenerator struct {
	buf strings.Builder
}

// NewSurfaceCodeGenerator creates a new surface code generator
func NewSurfaceCodeGenerator() *SurfaceCodeGenerator {
	return &SurfaceCodeGenerator{}
}

// GenerateSurfaceCircuit produces a surface code syndrome extraction round
func (g *SurfaceCodeGenerator) GenerateSurfaceCircuit(sc *sema.SurfaceCode) string {
	g.buf.Reset()
	d := sc.Distance

	g.buf.WriteString("// Generated by Karkain Compiler v1.1.0 — Surface Code Module\n")
	g.buf.WriteString(fmt.Sprintf("// Rotated surface code, distance d=%d\n", d))
	g.buf.WriteString(fmt.Sprintf("// %d data qubits, %d syndrome qubits\n", sc.DataQubits, sc.SyndromeQubits))
	g.buf.WriteString("OPENQASM 3.0;\n")
	g.buf.WriteString("include \"stdgates.inc\";\n")
	g.buf.WriteString("\n")
	g.buf.WriteString(fmt.Sprintf("qubit[%d] data;\n", sc.DataQubits))
	g.buf.WriteString(fmt.Sprintf("qubit[%d] x_syndrome;\n", len(sc.XStabilizers)))
	g.buf.WriteString(fmt.Sprintf("qubit[%d] z_syndrome;\n", len(sc.ZStabilizers)))
	g.buf.WriteString(fmt.Sprintf("bit[%d] x_out;\n", len(sc.XStabilizers)))
	g.buf.WriteString(fmt.Sprintf("bit[%d] z_out;\n", len(sc.ZStabilizers)))
	g.buf.WriteString("\n")

	g.buf.WriteString("// ---- X (Plaquette) Stabilizers ----\n")
	for i, stab := range sc.XStabilizers {
		g.buf.WriteString(fmt.Sprintf("// X stab %d: data qubits %v\n", i, stab))
		g.buf.WriteString(fmt.Sprintf("h x_syndrome[%d];\n", i))
		for _, dq := range stab {
			g.buf.WriteString(fmt.Sprintf("cx data[%d], x_syndrome[%d];\n", dq, i))
		}
		g.buf.WriteString(fmt.Sprintf("h x_syndrome[%d];\n", i))
		g.buf.WriteString(fmt.Sprintf("x_out[%d] = measure x_syndrome[%d];\n", i, i))
	}

	g.buf.WriteString("\n")

	g.buf.WriteString("// ---- Z (Vertex) Stabilizers ----\n")
	for i, stab := range sc.ZStabilizers {
		g.buf.WriteString(fmt.Sprintf("// Z stab %d: data qubits %v\n", i, stab))
		for _, dq := range stab {
			g.buf.WriteString(fmt.Sprintf("cx z_syndrome[%d], data[%d];\n", i, dq))
		}
		g.buf.WriteString(fmt.Sprintf("z_out[%d] = measure z_syndrome[%d];\n", i, i))
	}

	g.buf.WriteString("\n")
	g.buf.WriteString("// ---- Decoder ----\n")
	g.buf.WriteString("// Minimum-weight perfect matching / union-find decoder\n")
	g.buf.WriteString("// Correct errors on data qubits based on syndrome\n")

	return g.buf.String()
}

// ============================================================
// Code Properties Verifier
// ============================================================

func CommutesCheck(a, b sema.PauliString) bool {
	return sema.Commutes(a, b)
}

// VerifyCodeProperties checks stabilizer commutation and independence
func VerifyCodeProperties(code *sema.StabilizerCode) []string {
	var issues []string

	for i := 0; i < len(code.Generators); i++ {
		for j := i + 1; j < len(code.Generators); j++ {
			if !sema.Commutes(code.Generators[i], code.Generators[j]) {
				issues = append(issues, fmt.Sprintf(
					"generators %d and %d do not commute", i, j))
			}
		}
	}

	for i, lx := range code.LogicalX {
		for j, gen := range code.Generators {
			if !sema.Commutes(lx, gen) {
				issues = append(issues, fmt.Sprintf(
					"logical X[%d] does not commute with generator %d", i, j))
			}
		}
	}
	for i, lz := range code.LogicalZ {
		for j, gen := range code.Generators {
			if !sema.Commutes(lz, gen) {
				issues = append(issues, fmt.Sprintf(
					"logical Z[%d] does not commute with generator %d", i, j))
			}
		}
	}

	for i := 0; i < code.K; i++ {
		if i < len(code.LogicalX) && i < len(code.LogicalZ) {
			if sema.Commutes(code.LogicalX[i], code.LogicalZ[i]) {
				issues = append(issues, fmt.Sprintf(
					"logical X[%d] and Z[%d] should anticommute but commute", i, i))
			}
		}
	}

	return issues
}
