package codegen

import (
	"fmt"
	"karkain/pkg/parser"
	"strings"
)

// QIRGenerator generates QIR (Quantum Intermediate Representation) LLVM IR
// targeting the QIR Alliance specification
type QIRGenerator struct {
	buf        strings.Builder
	errors     []string
	qubitIDs   map[string]int // qubit name -> QIR qubit ID
	nextQubit  int
	nextResult int
	nextTemp   int
}

// NewQIRGenerator creates a new QIR LLVM IR generator
func NewQIRGenerator() *QIRGenerator {
	return &QIRGenerator{
		qubitIDs:  make(map[string]int),
		nextQubit: 0,
	}
}

// LLVM type name constants
const (
	qubitType = "%Qubit*"
	resultType = "%Result*"
)

// GenerateCircuit produces QIR LLVM IR from a CircuitDecl AST node
func (g *QIRGenerator) GenerateCircuit(circuit *parser.CircuitDecl) (string, error) {
	g.buf.Reset()
	g.errors = nil
	g.qubitIDs = make(map[string]int)
	g.nextQubit = 0
	g.nextResult = 0
	g.nextTemp = 0

	// LLVM IR header
	g.buf.WriteString("; Generated by Karkain Compiler v1.1.0 - QIR Backend\n")
	g.buf.WriteString("; Target: QIR Alliance Specification v1.0\n")
	g.buf.WriteString("\n")

	// QIR type declarations
	g.buf.WriteString("%Qubit = type opaque\n")
	g.buf.WriteString("%Result = type opaque\n")
	g.buf.WriteString("\n")

	// External function declarations (QIS intrinsics)
	g.buf.WriteString("declare void @__quantum__qis__h__body(%Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__x__body(%Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__y__body(%Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__z__body(%Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__rx__body(double, %Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__ry__body(double, %Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__rz__body(double, %Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__cnot__body(%Qubit*, %Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__cz__body(%Qubit*, %Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__swap__body(%Qubit*, %Qubit*)\n")
	g.buf.WriteString("declare %Result* @__quantum__qis__m__body(%Qubit*)\n")
	g.buf.WriteString("declare void @__quantum__qis__reset__body(%Qubit*)\n")
	g.buf.WriteString("\n")

	// Alloca qubits
	for _, param := range circuit.Params {
		size := 1
		if param.Type != nil && param.Type.Size > 0 {
			size = param.Type.Size
		}
		g.allocateQubits(param.Name, size)
	}

	g.buf.WriteString("\n")

	// Function signature
	retType := "void"
	if circuit.ReturnType != nil && circuit.ReturnType.Size > 0 {
		retType = resultType + "*"
	}

	g.buf.WriteString("define " + retType + " @" + circuit.Name + "(")

	params := make([]string, 0)
	for _, param := range circuit.Params {
		size := 1
		if param.Type != nil && param.Type.Size > 0 {
			size = param.Type.Size
		}
		if size > 1 {
			params = append(params, qubitType+"* "+param.Name)
		} else {
			params = append(params, qubitType+" "+param.Name)
		}
	}
	g.buf.WriteString(strings.Join(params, ", "))
	g.buf.WriteString(") {\n")
	g.buf.WriteString("entry:\n")

	// Store argument qubits into allocas
	for _, param := range circuit.Params {
		size := 1
		if param.Type != nil && param.Type.Size > 0 {
			size = param.Type.Size
		}
		if size > 1 {
			// For registers, we'd load individual qubits - simplified here
			for j := 0; j < size; j++ {
				qubitID := g.qubitIDs[fmt.Sprintf("%s[%d]", param.Name, j)]
				g.buf.WriteString(fmt.Sprintf("  ; qubit %s[%d] = %%arg.%s[%d]\n",
					param.Name, j, param.Name, j))
				_ = qubitID
			}
		} else {
			qubitID := g.qubitIDs[param.Name]
			g.buf.WriteString(fmt.Sprintf("  %%q.%d = alloca %%Qubit*\n", qubitID))
			g.buf.WriteString(fmt.Sprintf("  store %%Qubit* %%arg.%s, %%Qubit** %%q.%d\n",
				param.Name, qubitID))
		}
	}

	g.buf.WriteString("\n")

	// Generate gate operations
	g.generateBody(circuit.Body)

	// Return
	if circuit.ReturnType != nil && circuit.ReturnType.Size > 0 {
		g.buf.WriteString(fmt.Sprintf("  ret %s null\n", retType))
	} else {
		g.buf.WriteString("  ret void\n")
	}

	g.buf.WriteString("}\n")

	if len(g.errors) > 0 {
		return "", fmt.Errorf("QIR generation errors: %s", strings.Join(g.errors, "\n"))
	}
	return g.buf.String(), nil
}

// allocateQubits creates QIR qubit allocations
func (g *QIRGenerator) allocateQubits(name string, size int) {
	if size > 1 {
		g.buf.WriteString(fmt.Sprintf("; Qubit register %s[%d]\n", name, size))
		for i := 0; i < size; i++ {
			qubitName := fmt.Sprintf("%s[%d]", name, i)
			g.qubitIDs[qubitName] = g.nextQubit
			g.nextQubit++
		}
	} else {
		g.buf.WriteString(fmt.Sprintf("; Qubit %s\n", name))
		g.qubitIDs[name] = g.nextQubit
		g.nextQubit++
	}
}

// generateBody processes circuit body statements
func (g *QIRGenerator) generateBody(stmts []parser.Node) {
	for _, stmt := range stmts {
		g.generateStatement(stmt)
	}
}

// generateStatement emits QIR LLVM IR for a single statement
func (g *QIRGenerator) generateStatement(stmt parser.Node) {
	switch n := stmt.(type) {
	case *parser.ExprStmt:
		g.generateExpr(n.Expression)
	case *parser.QPUOpExpr:
		g.generateQPUOp(n)
	case *parser.CircuitReturnStmt:
		g.generateReturn(n)
	}
}

// generateExpr emits QIR for an expression
func (g *QIRGenerator) generateExpr(expr parser.Node) {
	switch n := expr.(type) {
	case *parser.QPUOpExpr:
		g.generateQPUOp(n)
	}
}

// generateQPUOp emits QIR LLVM IR for a quantum gate operation
func (g *QIRGenerator) generateQPUOp(op *parser.QPUOpExpr) {
	switch op.Op {
	case "h":
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__h__body(" + qubitType + " " + qubitRef + ")\n")
	case "x":
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__x__body(" + qubitType + " " + qubitRef + ")\n")
	case "y":
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__y__body(" + qubitType + " " + qubitRef + ")\n")
	case "z":
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__z__body(" + qubitType + " " + qubitRef + ")\n")
	case "rx":
		angle := g.formatLLVMExpr(op.Angle)
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__rx__body(double " + angle + ", " + qubitType + " " + qubitRef + ")\n")
	case "ry":
		angle := g.formatLLVMExpr(op.Angle)
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__ry__body(double " + angle + ", " + qubitType + " " + qubitRef + ")\n")
	case "rz":
		angle := g.formatLLVMExpr(op.Angle)
		qubitRef := g.resolveQubitRef(op.Args[0])
		g.buf.WriteString("  call void @__quantum__qis__rz__body(double " + angle + ", " + qubitType + " " + qubitRef + ")\n")
	case "cx":
		q0 := g.resolveQubitRef(op.Args[0])
		q1 := g.resolveQubitRef(op.Args[1])
		g.buf.WriteString("  call void @__quantum__qis__cnot__body(" + qubitType + " " + q0 + ", " + qubitType + " " + q1 + ")\n")
	case "cz":
		q0 := g.resolveQubitRef(op.Args[0])
		q1 := g.resolveQubitRef(op.Args[1])
		g.buf.WriteString("  call void @__quantum__qis__cz__body(" + qubitType + " " + q0 + ", " + qubitType + " " + q1 + ")\n")
	case "swap":
		q0 := g.resolveQubitRef(op.Args[0])
		q1 := g.resolveQubitRef(op.Args[1])
		g.buf.WriteString("  call void @__quantum__qis__swap__body(" + qubitType + " " + q0 + ", " + qubitType + " " + q1 + ")\n")
	case "measure":
		for _, arg := range op.Args {
			qubitRef := g.resolveQubitRef(arg)
			resultID := g.nextResult
			g.nextResult++
			g.buf.WriteString(fmt.Sprintf("  %%r.%d = call %s @__quantum__qis__m__body(", resultID, resultType))
			g.buf.WriteString(qubitType + " " + qubitRef + ")\n")
		}
	case "reset":
		for _, arg := range op.Args {
			qubitRef := g.resolveQubitRef(arg)
			g.buf.WriteString("  call void @__quantum__qis__reset__body(" + qubitType + " " + qubitRef + ")\n")
		}
	default:
		g.errors = append(g.errors, fmt.Sprintf("unknown QPU operation: %s", op.Op))
	}
}

// generateReturn emits return value
func (g *QIRGenerator) generateReturn(ret *parser.CircuitReturnStmt) {
	g.buf.WriteString("  ; return\n")
}

// resolveQubitRef returns the LLVM IR reference for a qubit
func (g *QIRGenerator) resolveQubitRef(node parser.Node) string {
	switch n := node.(type) {
	case *parser.Identifier:
		if id, ok := g.qubitIDs[n.Name]; ok {
			return fmt.Sprintf("%%q.%d", id)
		}
		return fmt.Sprintf("%%arg.%s", n.Name)
	case *parser.QubitIndexExpr:
		// For indexed access, compute the qubit ID
		qubitName := ""
		if ident, ok := n.Qubit.(*parser.Identifier); ok {
			qubitName = ident.Name
		}
		indexStr := g.formatLLVMExpr(n.Index)
		key := fmt.Sprintf("%s[%s]", qubitName, indexStr)
		if id, ok := g.qubitIDs[key]; ok {
			return fmt.Sprintf("%%q.%d", id)
		}
		// Fallback: compute at runtime (simplified)
		return fmt.Sprintf("%%q.%d /* %s */", 0, key)
	default:
		return "null"
	}
}

// formatLLVMExpr formats an expression for LLVM IR
func (g *QIRGenerator) formatLLVMExpr(node parser.Node) string {
	if node == nil {
		return "0.0"
	}
	switch n := node.(type) {
	case *parser.Identifier:
		return fmt.Sprintf("%%%s", n.Name)
	case *parser.IntLiteral:
		return n.Value
	case *parser.Float64Literal:
		return n.Value
	default:
		return "0.0"
	}
}

// GetErrors returns accumulated errors
func (g *QIRGenerator) GetErrors() []string {
	return g.errors
}
