package codegen

import (
	"fmt"
	"karkain/pkg/sema"
	"strings"
)

// ============================================================
// Phase 34: Optimized Quantum Circuit Codegen
// ============================================================

// QOptGenerator generates optimized quantum circuit code
type QOptGenerator struct {
	buf strings.Builder
}

// NewQOptGenerator creates a new optimized circuit generator
func NewQOptGenerator() *QOptGenerator {
	return &QOptGenerator{}
}

// GenerateCircuit produces OpenQASM 3.0 for a circuit
func (g *QOptGenerator) GenerateCircuit(c *sema.QCircuit) string {
	g.buf.Reset()

	g.buf.WriteString("// Generated by Karkain Compiler v1.0.0 — Optimized Circuit\n")
	g.buf.WriteString("OPENQASM 3.0;\n")
	g.buf.WriteString("include \"stdgates.inc\";\n")
	g.buf.WriteString("\n")
	g.buf.WriteString(fmt.Sprintf("qubit[%d] q;\n", c.NumQubits))
	g.buf.WriteString(fmt.Sprintf("bit[%d] c;\n", c.NumQubits))
	g.buf.WriteString("\n")

	for _, gate := range c.Gates {
		g.emitGate(gate)
	}

	return g.buf.String()
}

func (g *QOptGenerator) emitGate(gate sema.QGate) {
	switch {
	case len(gate.Controls) > 0:
		g.emitControlledGate(gate)
	case len(gate.Qubits) == 1 && isParametricQGate(gate.Name):
		g.buf.WriteString(fmt.Sprintf("%s(%.6f) q[%d];\n", gate.Name, gate.Angle, gate.Qubits[0]))
	case len(gate.Qubits) == 1:
		g.buf.WriteString(fmt.Sprintf("%s q[%d];\n", gate.Name, gate.Qubits[0]))
	case len(gate.Qubits) == 2:
		g.buf.WriteString(fmt.Sprintf("%s q[%d], q[%d];\n", gate.Name, gate.Qubits[0], gate.Qubits[1]))
	default:
		g.buf.WriteString(fmt.Sprintf("%s; // %v\n", gate.Name, gate.Qubits))
	}
}

func (g *QOptGenerator) emitControlledGate(gate sema.QGate) {
	if len(gate.Controls) == 1 && len(gate.Qubits) == 1 {
		if isParametricQGate(gate.Name) {
			g.buf.WriteString(fmt.Sprintf("c%s(%.6f) q[%d], q[%d];\n",
				gate.Name, gate.Angle, gate.Controls[0], gate.Qubits[0]))
		} else {
			g.buf.WriteString(fmt.Sprintf("c%s q[%d], q[%d];\n",
				gate.Name, gate.Controls[0], gate.Qubits[0]))
		}
	}
}

func isParametricQGate(name string) bool {
	switch name {
	case "rx", "ry", "rz", "crx", "cry", "crz", "p", "cp":
		return true
	}
	return false
}

// GenerateOptReport produces a human-readable optimization report
func (g *QOptGenerator) GenerateOptReport(result *sema.OptimizeResult) string {
	g.buf.Reset()

	g.buf.WriteString("╔══════════════════════════════════════════════╗\n")
	g.buf.WriteString("║   Quantum Circuit Optimization Report       ║\n")
	g.buf.WriteString("╠══════════════════════════════════════════════╣\n")
	g.buf.WriteString(fmt.Sprintf("║ Original gates:      %-23d║\n", result.OriginalGateCount))
	g.buf.WriteString(fmt.Sprintf("║ Optimized gates:     %-23d║\n", result.OptimizedGateCount))
	g.buf.WriteString(fmt.Sprintf("║ Gates removed:       %-23d║\n", result.GatesRemoved))
	g.buf.WriteString(fmt.Sprintf("║ Gates added:         %-23d║\n", result.GatesAdded))
	g.buf.WriteString(fmt.Sprintf("║ Original depth:      %-23d║\n", result.OriginalDepth))
	g.buf.WriteString(fmt.Sprintf("║ Optimized depth:     %-23d║\n", result.OptimizedDepth))
	g.buf.WriteString(fmt.Sprintf("║ Depth reduction:     %-23d║\n", result.DepthReduction))
	g.buf.WriteString(fmt.Sprintf("║ Iterations:          %-23d║\n", result.Iterations))
	g.buf.WriteString("╚══════════════════════════════════════════════╝\n")

	return g.buf.String()
}

// GenerateCircuitStatsReport produces a stats report
func (g *QOptGenerator) GenerateCircuitStatsReport(c *sema.QCircuit) string {
	stats := sema.ComputeStats(c)
	g.buf.Reset()

	g.buf.WriteString("╔══════════════════════════════════════════════╗\n")
	g.buf.WriteString("║   Circuit Statistics                         ║\n")
	g.buf.WriteString("╠══════════════════════════════════════════════╣\n")
	g.buf.WriteString(fmt.Sprintf("║ Total gates:         %-23d║\n", stats.TotalGates))
	g.buf.WriteString(fmt.Sprintf("║ Two-qubit gates:     %-23d║\n", stats.TwoQubitGates))
	g.buf.WriteString(fmt.Sprintf("║ Depth:               %-23d║\n", stats.Depth))
	g.buf.WriteString(fmt.Sprintf("║ Width (qubits):      %-23d║\n", stats.Width))
	g.buf.WriteString(fmt.Sprintf("║ T gates:             %-23d║\n", stats.TGateCount))
	g.buf.WriteString(fmt.Sprintf("║ Parameterized gates: %-23d║\n", stats.Parameterized))
	g.buf.WriteString("║ Gate breakdown:                                ║\n")
	for name, count := range stats.GateCounts {
		g.buf.WriteString(fmt.Sprintf("║   %-16s %-23d║\n", name, count))
	}
	g.buf.WriteString("╚══════════════════════════════════════════════╝\n")

	return g.buf.String()
}
