# Generates src/compiler/conc_runtime.kark from runtime/concurrency/c/*.
#
# Phase 137: the self-hosted compiler embeds the concurrency C runtime as
# emitLine one-liners (the same style as its Value/net runtimes), because
# Karkain has no file-embedding builtin. This script is the single
# implementation of that transform - never hand-edit the generated file.
# Rerun after touching runtime/concurrency/c/*:
#   pwsh scripts/gen-conc-runtime.ps1   (or powershell -File ...)
#
# A Go freshness gate (pkg/codegen TestConcRuntimeKarkFresh) compares the
# per-file SHA-256 recorded in the header and fails with this command when
# the runtime sources drift.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$srcDir = Join-Path $root "runtime/concurrency/c"
$outPath = Join-Path $root "src/compiler/conc_runtime.kark"

$files = @("karkain_conc.h", "karkain_sched_impl.h", "karkain_channel.c", "karkain_actor.c", "karkain_scheduler.c")

function Escape-KarkString([string]$s) {
    # Order matters: backslashes first, then quotes. CR already stripped by
    # line splitting; non-ASCII bytes pass through verbatim (UTF-8).
    return $s.Replace("\", "\\").Replace('"', '\"')
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Generated by scripts/gen-conc-runtime.ps1 - DO NOT EDIT BY HAND.")
[void]$sb.AppendLine("// Phase 137: concurrency C runtime embedded for the self-hosted")
[void]$sb.AppendLine("// backend. Regenerate with: pwsh scripts/gen-conc-runtime.ps1")
$digests = @()
foreach ($f in $files) {
    $p = Join-Path $srcDir $f
    $bytes = [System.IO.File]::ReadAllBytes($p)
    # LF-normalize before hashing: Windows checkouts carry CRLF while Linux
    # checkouts carry LF, and the digest must agree on both (the Go gate
    # normalizes the same way). The embedded emitLine body is already
    # LF-clean via the '\r?\n' split below, so only the digest needs this.
    $norm = $bytes | Where-Object { $_ -ne 13 }
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hex = ($sha.ComputeHash($norm) | ForEach-Object { $_.ToString("x2") }) -join ""
    $digests += "$f=$hex"
}
[void]$sb.AppendLine("// runtime-sha256: " + ($digests -join " "))
[void]$sb.AppendLine("")
[void]$sb.AppendLine("// emitConcRuntime appends the runtime core (header + impl headers +")
[void]$sb.AppendLine("// channel/actor/scheduler bodies, self-includes stripped exactly like")
[void]$sb.AppendLine("// the Go backend's stripEmbedInclude) to the generated C unit.")
[void]$sb.AppendLine("func emitConcRuntime(state) {")

foreach ($f in $files) {
    [void]$sb.AppendLine('    emitLine(state, "// ==== Phase 107 runtime source: ' + $f + ' ====")')
    # UTF-8 throughout: the C sources contain non-ASCII comment text that
    # must survive byte-identically (default ReadAllText would ANSI-decode).
    $text = [System.IO.File]::ReadAllText((Join-Path $srcDir $f), [System.Text.Encoding]::UTF8)
    foreach ($line in $text -split '\r?\n') {
        $t = $line.Trim()
        if ($t.StartsWith('#include "karkain_conc.h"') -or $t.StartsWith('#include "karkain_sched_impl.h"')) {
            continue
        }
        [void]$sb.AppendLine('    emitLine(state, "' + (Escape-KarkString $line) + '")')
    }
}
[void]$sb.AppendLine("}")

$final = $sb.ToString() -replace '\r(?=\n)', ''
[System.IO.File]::WriteAllText($outPath, $final, (New-Object System.Text.UTF8Encoding $false))
Write-Host "wrote $outPath"
